### ISSUE TITLE
Support for non-English localizations

### ISSUE THREAD

**Issue by boettges** [xilopaint/alfred-things#1]
Hello,
right now the icon for the default lists (Today, Someday, Trash …) are hard-coded into the script as the [array "stdLists"](https://github.com/xilopaint/alfred-things/blob/2a70a954152655d5d128b80509f11d99ed459b09/src/things.applescript#L47).
The array items call the respectively named icon-png.

Upon the first run the AppleScript could query the system localization and save it as a parameter. Depending on the system's localization the list names could be matched with the respecitve icons.

The German list names are:
`{"Eingang", "Heute", "Geplant", "Jederzeit", "Irgendwann", "Logbuch", "Papierkorb"}`

Let me know if I can help 👌
Best regards

**Comment by xilopaint** [comment]
Done in v1.4.

![screen shot 2017-11-08 at 02 56 56](https://user-images.githubusercontent.com/11052366/32534470-8f6579dc-c434-11e7-907e-88481281a76a.png)

![screen shot 2017-11-08 at 02 59 21](https://user-images.githubusercontent.com/11052366/32534481-97bb4bc0-c434-11e7-8aed-cfc896393e39.png)

**Comment by boettges** [comment]
Amazing 👌 
a very simple solution with the fixed counter, as the lists are in the same order in all localizations.

Just to understand the code of the AppleScript better, why the null in [line 47](https://github.com/xilopaint/alfred-things/blob/6f6c60d4639fe0da51fd06708b66b64219ca50ed/src/things.applescript#L47)?

Thanks a lot!

**Comment by xilopaint** [comment]
The 6th item of `lists` is an awkward `Lonely Projects` list. I don't have a clue what it's meant to represent as it doesn't appear in Things UI.

The loop block handles this situation to ensure this list will not be displayed in Alfred.

**Comment by boettges** [comment]
Sorry to bother you again, but the non-English locale is broken again since 1.4.1. 
The icons are not shown:
![bildschirmfoto 2018-02-16 um 09 25 19](https://user-images.githubusercontent.com/20265197/36299051-70acff54-12fb-11e8-972f-865b121af63a.png)

It however worked flawlessly in 1.4.0 🤔

**Comment by xilopaint** [comment]
Oh, sorry! I've committed a stupid mistake in v1.4.1. I am releasing the fix in the next few minutes. Thanks for spotting the bug again.
