### ISSUE TITLE
List projects in higher level list instead of navigating inside a area 

### ISSUE THREAD

**Issue by preems** [xilopaint/alfred-things#10]
Also if there is a project outside of Area, there is no way to access that.

**Comment by xilopaint** [comment]
> Also if there is a project outside of Area, there is no way to access that.

The projects are accessible in the lists that contain them.

**Comment by xilopaint** [comment]
Hey @preems, could you explain your issue better?

**Comment by xilopaint** [comment]
Hey, I'm closing the issue for now. If you get back with some explanation I'll reopen it.
