### ISSUE TITLE
[Feature Request] Creating tasks with sequential numbers?

### ISSUE THREAD

**Issue by realliyifei** [xilopaint/alfred-things#11]
When using Things, we always need to create tasks with a shared name plus sequential numbers.

Example 1: chapter 1, chapter 2, chapter 3, chapter 4

Example 2: ML assn 09, ML assn 10, ML assn 11

Is it possible to create a script that generates them at once? For example, in example 1, we may just type: `chapter {1-4}`

It would be better to provide an option to choose creating *tasks with sequential numbers* or *a task with multiple sequential checklists*

**Comment by xilopaint** [comment]
Sorry, @yif-li, but adding a functionality for creating tasks is not on the plans. Because of the power of the built-in quick entry panel, I came to the conclusion this workflow cannot add any value to the UX despite in niche cases like yours.
