### ISSUE TITLE
Cannot parse json

### ISSUE THREAD

**Issue by spearkkk** [xilopaint/alfred-things#13]
Hi, i am spearkkk
First of all, I appreciate your share and nice workflow.
I like this workflow and use much.

I find there is issue in parsing data if there is double quote in data.

Could you fix this issue using another replacement char?

The followings is full error message:

`[22:27:56.721] ERROR: Things[Script Filter] JSON error: Badly formed object around character 3282. in JSON:
{"items": [{"title": "Back to Lists", "subtitle": "", "arg": "back", "valid": true, "icon": {"path": "icons/back.png"}, "mods": "" }, {"title": "wrjlewis/notion-search-alfred-workflow: An Alfred workflow to search Notion with instant results", "subtitle": "", "arg": "2316D5B1-DAA8-41F6-8128-392C45494847", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "kevinjalbert/notion-toolbox: This is a collection of Notion tools that work in tandem together.", "subtitle": "", "arg": "6ABD70CB-221F-457F-BDEB-11D691E285E8", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "fniephaus/alfred-pocket: Manage your Pocket list with Alfred", "subtitle": "", "arg": "02A0730B-7F5F-414A-9CC9-4EBC6FBE76B3", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "xilopaint/alfred-things: Interact with Things 3 using Alfred.", "subtitle": "", "arg": "3BDB927C-28B6-4929-909B-3734F90D23BF", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "willfarrell/alfred-encode-decode-workflow: Encoding and decoding a sting into multiple variations.", "subtitle": "", "arg": "2891D8A8-7193-42BB-9405-7676B1CDB883", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "jsumners/alfred-emoji: Alfred workflow for searching and copying emoji", "subtitle": "", "arg": "03D64809-AADA-434B-AF65-0935B57B1E37", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "tilmanginzel/alfred-bluetooth-workflow: Yet another Alfred workflow to connect / disconnect Bluetooth devices", "subtitle": "", "arg": "D6DFD1C7-5629-4CCB-A677-99D2845DDF16", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "vitorgalvao/custom-iterm-scripts-for-alfred: Custom iTerm Scripts for Alfred", "subtitle": "", "arg": "F20D4DC0-8AED-4C4C-A584-57AB7C5F9CEB", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "bchatard/alfred-jetbrains: Alfred3 workflow to easily open your projects with your favorite JetBrains product.", "subtitle": "", "arg": "6113E516-429C-45BA-A1E6-AF03BA0D0A1A", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "small-workflows/local-host at master · nikitavoloboev/small-workflows", "subtitle": "", "arg": "E9309711-6789-4A44-B479-F94D29C908A5", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "small-workflows/folder-search at master · nikitavoloboev/small-workflows", "subtitle": "", "arg": "4A14B42B-41D6-4D85-9E14-672864E3A318", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "small-workflows/search-content at master · nikitavoloboev/small-workflows", "subtitle": "", "arg": "86FAAB20-D8E1-42C6-96D6-1B5D81C19BFD", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "small-workflows/file-actions at master · nikitavoloboev/small-workflows", "subtitle": "", "arg": "D62929F7-8D88-4D16-B9C8-8E3C19EC75DB", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "small-workflows/wifi-tools at master · nikitavoloboev/small-workflows", "subtitle": "", "arg": "990DA9F3-1628-449D-81ED-4F940743C056", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }, {"title": "Understanding "Query Then Fetch" vs "DFS Query Then Fetch" | Elastic Blog", "subtitle": "", "arg": "5C9156AD-0DE6-4907-84B7-A090021E00CF", "valid": true, "icon": {"path": "icons/todo.png"}, "mods": "" }]}`

**Comment by xilopaint** [comment]
Sorry for the late response. Could you give me the steps on how to reproduce the issue? In the following example with double quotes in the title the workflow is working fine:

![Screen Shot 2020-06-28 at 05 51 59](https://user-images.githubusercontent.com/11052366/85943085-174ab080-b904-11ea-984b-ad86a9eb988f.png)

**Comment by deanishe** [comment]
> In the following example with double quotes in the title the workflow is working fine:

Those are fancy quotes `“”`, not regular quotes `"`.

The issue is easily reproducible by adding an item with normal, ASCII quotes in its title.

**Comment by xilopaint** [comment]
I fear that fixing this issue could imply in a substancial change to the library's code base. Would you like to submit a PR, @spearkkk?

**Comment by spearkkk** [comment]
@xilopaint , Actually I don`t know about applescript well, but I will try it.
If I fix it, let you know it and request PR. 
Thank you.
