### ISSUE TITLE
Filter by tags

### ISSUE THREAD

**Issue by jbusecke** [xilopaint/alfred-things#15]
Thanks for putting together this amazing workflow!

Would it be possible to query a tag (either globally) or even within a project or the Inbox? 

An example: I tag very short tasks (able to achieve in a break) with `short`. It would be fantastic if I could see all these tasks by typing `todo "short"` or similar.

**Comment by xilopaint** [comment]
> Would it be possible to query a tag (either globally) or even within a project or the Inbox?

Sorry for the late response. Are you aware you can show tags in a list with `⌃ ↵`?

**Comment by jbusecke** [comment]
I was not, until now. Thank you.
