### ISSUE TITLE
Add Todo Issue

### ISSUE THREAD

**Issue by RyanBeckett** [xilopaint/alfred-things#16]
` ⌥ + ↩  to add a to-do to the selected list;
`

This keyboard shortcut does not work for me. Has been tested in Inbox, Today, Selected Project, Selected Area, Selected Area > Selected Project.

Thanks.

Alfred Version: Version 1.7.1
MacOS: 10.15.5

**Comment by xilopaint** [comment]
Sorry, I rephrased the description in README. Since v1.7 this modifier key invokes the Quick Entry window that enables you to add to-dos. Is it working for you?
