### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by h-jia** [xilopaint/alfred-things#17]
Closed

**Comment by xilopaint** [comment]
Sorry for the late response. It works normally for me on Big Sur. Could you provide the debugger's log?.

**Comment by xilopaint** [comment]
Sorry for the late response. It works normally for me on Big Sur. Could you provide the debugger's log?

**Comment by h-jia** [comment]
Thanks for response. It seems the `show lists` did not respond the key `todo`. Please see attached file below:

![image](https://user-images.githubusercontent.com/29906369/103351583-d07a8500-4af7-11eb-8b21-a2b2cd898e23.jpeg)

**Comment by xilopaint** [comment]
Please, post the log or I'll not be able to debug your issue.

**Comment by h-jia** [comment]
humm. ok. let me search how to debug the log and back to you.

**Comment by h-jia** [comment]
Give in. Don't know how to work.
