### ISSUE TITLE
Search for todos

### ISSUE THREAD

**Issue by gasperphoenix** [xilopaint/alfred-things#26]
Hi, good plugin, thx :-)

Would it be possible to extend the workflow to search for todos in Things?

I'm using an Alfred workflow for Apple Notes which has a similar capability but also provides the ability to search for notes.

That would be a great extension for your workflow.

**Comment by xilopaint** [comment]
Sorry, I don't get what you mean. To-do search is the main feature of this workflow.

**Comment by gasperphoenix** [comment]
Could you please explain how I can search for a specific todo title? If I type _todo_ it shows the list from your screenshot including the main lists and areas. I can open the lists to view the content and add new todos etc. But I can't figure out how to search for a specific item in my complete things database.

**Comment by xilopaint** [comment]
When you select a list you should see the contained todos:

![todo](https://user-images.githubusercontent.com/11052366/224390334-20c7804d-e533-4fd4-b109-9b3c958abf5a.png)

**Comment by gasperphoenix** [comment]
Yes, I know. I thought I could search for a specific entry. Let's assume I have a todo like "Plan summer vacation". It would be great if I could start up Alfred and search for it. Something like:

"todo summer"  ==> shows all things entries matching _summer_ in title (notes / projects / areas) or included notes

**Comment by gasperphoenix** [comment]
If I don't know in which specific list this item is included I would need to start things to search for it otherwise

**Comment by xilopaint** [comment]
> Yes, I know. I thought I could search for a specific entry. Let's assume I have a todo like "Plan summer vacation". It would be great if I could start up Alfred and search for it. Something like:
> 
> "todo summer" ==> shows all things entries matching _summer_ in title (notes / projects / areas) or included notes

I'm afraid it's not something easy to implement with AppleScript. Large databases can make searching very slow.

**Comment by gasperphoenix** [comment]
😔 ok

**Comment by xilopaint** [comment]
I have plans to rewrite this workflow in JXA and will consider your request at this time. But again, I'm not sure if I'll have a viable implementation for it. At this moment, I'm closing the issue and can reopen in the future if I find a good solution.

**Comment by cDavid2020** [comment]
> If I don't know in which specific list this item is included I would need to start things to search for it otherwise

Cultured code has a CLI plugin that does what you mentioned 

https://github.com/itspriddle/things-cli
