### ISSUE TITLE
Add new notes

### ISSUE THREAD

**Issue by ritave** [xilopaint/alfred-things#27]
I would like to have an ability to add a new note using `+Buy milk [shopping] today 9:00` syntax or similar, the initial `+` is the important feature.

**Comment by xilopaint** [comment]
Do you mean a new to-do?

**Comment by ritave** [comment]
Yeah

**Comment by xilopaint** [comment]
How can this be any better than the built-in Quick Entry panel?

**Comment by ritave** [comment]
Natural language input, more similar to how brains think, less keywords to remember, singular flow.

If you ever have a chance, try [Fantastical](https://flexibits.com/fantastical) for example. `Coffee with xilopaint, 10:20 CEST, @Cafe Corner`, it so much more enjoyable than filling things in interfaces.

**Comment by xilopaint** [comment]
I really can't see this as a better alternative than Quick Entry. After invoking the Quick Entry panel and typing the to-do title, you can repeatedly hit tab and fill in whatever you want without taking your hands off the keyboard (notes, date, checklist, tags, deadline and list). A comprehensive syntax for all these details will hardly be as simple as just using Quick Entry.

**Comment by cDavid2020** [comment]
> How can this be any better than the built-in Quick Entry panel?

Quick Entry only works when Things/Things Helper is running as a process. This makes it convenient without having it open.

**Comment by xilopaint** [comment]
> Quick Entry only works when Things/Things Helper is running as a process. This makes it convenient without having it open.

This workflow only works when Things is running. If Things is not open the workflow will open it.

Using `⌥ ↵` with the workflow opens Quick Entry.

**Comment by ritave** [comment]
@xilopaint generally I moved to RayCast, but if you have the chance, try using https://flexibits.com/fantastical for 5 minutes. The natural language input is just joyful to use, maybe not faster, but joyful.

In any case, I enjoyed using alfred-things while I had the chance, thank you for making it.

**Comment by xilopaint** [comment]
> @xilopaint generally I moved to RayCast

I just tried the "Add New To-Do" command from the Things Raycast extension and it looks pretty decent.

**Comment by ritave** [comment]
Yeah, it's not bad, setting the list to a specific date in the future is annoying, but the ecosystem in general is decent.

I recorded this for you.
https://github.com/xilopaint/alfred-things/assets/1614945/7909a6c6-33df-4233-ace4-e33bb805e066

**Comment by xilopaint** [comment]
I would accept a PR adding natural language support if it's really easy to use and covers at least date, tags, deadline and list.
