### ISSUE TITLE
It occurred an error!

### ISSUE THREAD

**Issue by BlasphemyAngels** [xilopaint/alfred-things#3]
When I use the workflow, it didn't work, So I debug it an get the follow info.
![error](https://i.loli.net/2018/02/06/5a79666ca82ce.png)

**Comment by xilopaint** [comment]
What versions of Alfred, Things app and Things workflow are you running? Could you change your OS X language to English, restart Things app and tell me if it works this way?

**Comment by xilopaint** [comment]
Please, provide more details or this issue will be closed.

**Comment by xilopaint** [comment]
Hey, @BlasphemyAngels, your issue should be fixed on the latest release.
