### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by jenderle7** [xilopaint/alfred-things#4]
The todo trigger pulls up the available lists but when I choose one and type out a todo and hit enter nothing happens. Keep in mind I'm new to using these workflows in Alfred but it's the only one out of dozens I can't seem to get working. Using Alfred v3.6 on High Sierra v10.13.3

**Comment by xilopaint** [comment]
Please, paste here the output of the [Workflow Debbuger](https://www.alfredapp.com/help/workflows/advanced/debugger/) after trying to use the workflow as described.

**Comment by jenderle7** [comment]
[2018-03-14 16:23:25][input.scriptfilter] Queuing argument '(null)'
[2018-03-14 16:23:25][input.scriptfilter] Script with argument '(null)' finished
[2018-03-14 16:23:25][input.scriptfilter] <?xml version="1.0"?>
<items>
	<item arg="Inbox">
		<title>Inbox</title>
		<subtitle></subtitle>
		<icon>icons/inbox.png</icon>
	</item>
	<item arg="Today">
		<title>Today</title>
		<subtitle></subtitle>
		<icon>icons/today.png</icon>
	</item>
	<item arg="Anytime">
		<title>Anytime</title>
		<subtitle></subtitle>
		<icon>icons/anytime.png</icon>
	</item>
	<item arg="Upcoming">
		<title>Upcoming</title>
		<subtitle></subtitle>
		<icon>icons/upcoming.png</icon>
	</item>
	<item arg="Someday">
		<title>Someday</title>
		<subtitle></subtitle>
		<icon>icons/someday.png</icon>
	</item>
	<item arg="Logbook">
		<title>Logbook</title>
		<subtitle></subtitle>
		<icon>icons/logbook.png</icon>
	</item>
	<item arg="Trash">
		<title>Trash</title>
		<subtitle></subtitle>
		<icon>icons/trash.png</icon>
	</item>
	<item arg="UIC">
		<title>UIC</title>
		<subtitle></subtitle>
		<icon>icons/area.png</icon>
	</item>
	<item arg="Design">
		<title>Design</title>
		<subtitle></subtitle>
		<icon>icons/area.png</icon>
	</item>
	<item arg="Home">
		<title>Home</title>
		<subtitle></subtitle>
		<icon>icons/area.png</icon>
	</item>
	<item arg="Work">
		<title>Work</title>
		<subtitle></subtitle>
		<icon>icons/area.png</icon>
	</item>
</items>
[2018-03-14 16:23:31][input.scriptfilter] Processing output of 'utility.argument' with arg 'Today'
[2018-03-14 16:23:31][utility.argument] Processing output of 'output.callexternaltrigger' with arg 'Today'
[2018-03-14 16:23:31][trigger.external] Processing output of 'input.scriptfilter' with arg ''
[2018-03-14 16:23:31][input.scriptfilter] Processing output of 'action.script' with arg 'Today'
[2018-03-14 16:23:31][input.scriptfilter] Queuing argument '(null)'
[2018-03-14 16:23:31][input.scriptfilter] Script with argument '(null)' finished
[2018-03-14 16:23:31][input.scriptfilter] <?xml version="1.0"?>
<items>
	<item arg="back">
		<title>Back to Lists</title>
		<subtitle>Empty list</subtitle>
		<icon>icons/back.png</icon>
	</item>
</items>

**Comment by xilopaint** [comment]
What version of the workflow are you running and how many tasks do you have in Today list?

**Comment by jenderle7** [comment]
v1.4.3 and 0 tasks

**Comment by xilopaint** [comment]
What do you intend to do? Hitting `return` in Today list is supposed to show your to-dos in this list. Since you don't have any to-dos in there getting nothing is expected behaviour for you.

**Comment by jenderle7** [comment]
Yeah I apologize. I completely misunderstood the usage of this workflow. I thought I was choosing a list and then creating/adding a todo to that list, hence return not triggering anything. Anyways sorry to waste your time.

**Comment by xilopaint** [comment]
Indeed you can add a to-do to a list using the ⌥ modifier key.
