### ISSUE TITLE
Add ability to add a Things todo from Alfred

### ISSUE THREAD

**Issue by felciano** [xilopaint/alfred-things#5]
Thank you for making this workflow available. It would be great to also us this to add new Todo items to Things.

**Comment by areohbe** [comment]
@felciano thanks for adding this, might add a few additions to your PR. Before I do that, is there any way to set the due date when creating a new within the Alfred workflow?

**Comment by felciano** [comment]
No clue -- I'll defer to @xilopaint to answer that. I'm just trying to document what I figured out by experimenting.

**Comment by xilopaint** [comment]
@areohbe no, set a due date while creating a new to-do is not currently possible. Have you ever taken a look at Thing's Quick Entry feature?

![screen shot 2018-10-24 at 23 31 00](https://user-images.githubusercontent.com/11052366/47472368-e6d47a00-d7e4-11e8-8446-09669b6edfc2.png)

I really don't see how my workflow can be better than it for the purpose of creating new to-dos. Personally, I don't even use this workflow for adding new to-dos to Things.

**Comment by xilopaint** [comment]
@felciano what is this issue about? Is it about creating to-dos or improving README?
