### ISSUE TITLE
Would be great to have a dedicated keyword for a new task

### ISSUE THREAD

**Issue by seanonthenet** [xilopaint/alfred-things#7]
Thanks for the workflow. 
Would be great if it included a keyword for a quick adding a new todo. 
EG: "newtodo Pick up laundry"
This would be a little more efficient and faster as one string (<keyword><space><todo>) than the current method (<keyword><cmd><enter><todo>)

I know that Things itself has its own shortcut but I do nearly everything with Alfred so I don't remember any shortcuts for anything else. 

Thanks

**Comment by seanonthenet** [comment]
stripped content

> This would be a little more efficient and faster as one string () than the current method ()

Stripped content was: 
This would be a little more efficient and faster as one string (keyword)(space)(todo) than the current method (keyword)(cmd)(enter)(todo)

**Comment by xilopaint** [comment]
> This would be a little more efficient and faster as one string (keyword)(space)(todo) than the current method (keyword)(cmd)(enter)(todo)

Unlike the current implementation, your suggestion doesn't enable the user to select a list for the to-do.

**Comment by seanonthenet** [comment]
I think that's what Inbox is for. For as yet unlisted tasks.

**Comment by xilopaint** [comment]
So do you suggest to have a keyword for creating to-dos in Inbox?

**Comment by xilopaint** [comment]
@Spark3000 I'm closing the issue until you want resume the discussion.
