### ISSUE TITLE
TODO TODAY [enter] returns empty

### ISSUE THREAD

**Issue by haakonstorm** [xilopaint/alfred-things#8]
TODO TODAY [enter] returns empty
All the other lists works
Great workflow!
How to fix "today"? :)

**Comment by xilopaint** [comment]
I can't reproduce your issue. Any chance you have a great amount of to-dos on Today list? In this case, the workflow can need some time to fetch your to-dos, so you just need waiting enough.

If that is not the cause of your issue, please provide the logs by using the [workflow debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/).

**Comment by haakonstorm** [comment]
Hah, that fixed it, I had to let it sit for close to a minute. After that, now everything works instantly. Great workflow!

**Comment by xilopaint** [comment]
Good to know is everything ok to you. I'm closing the issue.
